### ISSUE TITLE
better-defaults

### ISSUE THREAD

**Issue by jgarte** [mizlan/.emacs.d#1]
What do you think of refactoring `(menu-bar-mode -1)` and other similar settings with requiring technomancy's [better-defaults](https://git.sr.ht/~technomancy/better-defaults/tree/master/item/better-defaults.el)? 

Or, is it too heavy-handed?

I started just including better-defaults as a base on top of my emacs config since I agree with most of its settings and I understand what that package's code is doing.

**Comment by mizlan** [comment]
Cool, thanks for sharing this, I wasn't aware about this! I'll add this.

**Comment by jgarte** [comment]
> Cool, thanks for sharing this, I wasn't aware about this! I'll add this.

Cool! I started using `better-defaults` a few weeks ago and so far I'm happy with the boilerplate it saves me of defaults that I usually want in my init.el 😄
